version: '3.9'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: naneka_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: naneka
      POSTGRES_USER: naneka_user
      POSTGRES_PASSWORD: changeme
    ports:
      - '5432:5432'
    volumes:
      - naneka_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: naneka_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: naneka_frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  waha:
    image: devlikeapro/waha
    container_name: naneka_waha
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      WHATSAPP_API_KEY: Naneka_RsHP2pA9a_32n3ObL5Y_dZRe
      WHATSAPP_HOOK_URL: https://naneka-backend.vercel.app/webhooks/waha
      WHATSAPP_HOOK_EVENTS: message,session.status
      WHATSAPP_DEFAULT_ENGINE: WEBJS
    volumes:
      - naneka_waha_data:/app/.waha/sessions

volumes:
  naneka_pgdata:
  naneka_waha_data:
